spring:
  application:
    name: parking-roles

  datasource:
    url: jdbc:postgresql://localhost:5432/parkingdb
    username: admin
    password: admin

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://cognito-idp.us-east-1.amazonaws.com/us-east-1_lsXiNJuAX

server:
  port: 8787

logging:
  level:
    org.springframework.security: INFO